import sys, os
import numpy as np
import pdb
import warnings

def load_one_label_seq(path):
    npy = np.load(path)
    return npy


def load_label_seqs(path, mode, index):#index are generated by gen_index
    labels=[]
    for i in range(len(index)): #eg index = [(lab,1),(lab,2),(lab,3),...]
        loc = index[i][0] #eg lab office house
        idx = index[i][1] #eg 1,2,3
        labelnpy = os.path.join(path,loc,mode+"_left"+str(idx)+'.npy')
        labels.append(load_one_label_seq(labelnpy))
        #labelnpy = os.path.join(path,loc,mode+"_right"+str(idx)+'.npy')
        #labels.append(load_one_label_seq(labelnpy))
    for i in range(len(index)):
        loc = index[i][0]
        idx = index[i][1]
        #labelnpy = os.path.join(path,loc,mode+"_left"+str(idx)+'.npy')
        #labels.append(load_one_label_seq(labelnpy))
        labelnpy = os.path.join(path,loc,mode+"_right"+str(idx)+'.npy')
        labels.append(load_one_label_seq(labelnpy))
    return labels #left1~3 right1~3

def gen_index(setting_index):
    train_index=[]
    test_index =[]
    if setting_index == 0:
        #order: 
            #train : lab1~4  off1~3  house1~3
            #test  : lab5~8  off4~6  house4~6
        for i in range(1,7):
            if i <= 3:
                train_index.append(('house',i))
            else:
                test_index.append(('house',i))
        for i in range(1,9):
            if i <= 4:
                train_index.append(('lab',i))
            else:
                test_index.append(('lab',i))
        for i in range(1,7):
            if i <= 3:
                train_index.append(('office',i))
            else:
                test_index.append(('office',i))

    elif setting_index == 1:
        for i in range(1,9):
            train_index.append(('lab',i))
        for i in range(1,7):
            train_index.append(('office',i))
        for i in range(1,7):
            test_index.append(('house',i))
    else:
        raise ValueError ('error setting index')

    return train_index, test_index



def gen_index_process(index=None, setting_index=None):
    if index == None:
        if setting_index==None:
            raise ValueError('Setting index can not be none')
        else:
            train_index, test_index = gen_index(setting_index)
    return train_index, test_index
    

def load_train_labels(path, mode, index=None, setting_index=None):
    if index == None:
        index,_ = gen_index_process(index,setting_index)
    else:
        if setting_index != None:
            warnings.warn('setting_index has no effect when given particular index')
    labels = load_label_seqs(path, mode, index)
    return labels

def load_test_labels(path, mode, index=None, setting_index=None):
    if index == None:
        _,index = gen_index_process(index,setting_index)
    else:
        if setting_index != None:
            warnings.warn('setting_index has no effect when given particular index')
    labels = load_label_seqs(path, mode, index)
    return labels


def load_all_labels(path, mode, setting_index):
    train_index, test_index = gen_index(setting_index)
    train_labels = load_train_labels(path, mode,train_index)
    test_labels = load_train_labels(path, mode,test_index)
    return train_labels, test_labels